export VSPHERE_VCENTER='172.16.1.10'
export VSPHERE_USERNAME='REMOVED'
export VSPHERE_PASSWORD='REMOVED'
export VSPHERE_NETWORK='DPortGroup No LACP'
export VSPHERE_DATASTORE='RAID5-Datastore1-NFS'
export VSPHERE_DATACENTER='DC1'
export VSPHERE_HOSTSYSTEM='AMD Cluster/172.16.1.15'
#export VSPHERE_POOL
